(library
  (public_name elm_playground_native)
  (implements elm_playground)
  ; problems with tsdl on windows I think
  (libraries
    str
    logs
    cairo2 tsdl
    stb_image ; Image_decode.image's fields, in Image_native

    elm_playground
    elm_playground_native_common ; Native_loop_2d
    graphics_images ; Image_decode
  )
)
