(library
 (public_name elm_playground_3d_opengl)
 (implements elm_playground_3d)
 (libraries
   tsdl
   tgls.tgl3
   threads.posix ; tgls/ctypes-foreign needs this to link, even though we don't use threads ourselves
   stb_image ; Stb_image.t, used by the type of get_or_create_gl_texture (Texture_native itself lives in elm_playground_3d_native_common)
   elm_core
   elm_playground
   elm_playground_3d
   elm_playground_3d_native_common ; SDL event loop + Texture_native
 )
)
