(executables
  (names 
    Picture Smiley Words Misc
    Animation 
    Mouse Keyboard Turtle Mario
    Flags
    Orbit Bounce Marbles Boxes Pyramid Elastic SolarSystem Theremin Piano
    Fractals
  )
  (libraries
    elm_playground
    elm_playground_native ; implem of virtual elm_playground
  )
)
