(executables
  (names 
    Picture Smiley Words Misc
    Animation 
    Mouse Keyboard Turtle Mario
    Flags
    PhysicsOrbit PhysicsBounce PhysicsMarbles PhysicsBoxes PhysicsPyramid PhysicsElastic PhysicsSolarSystem Theremin Piano
    LogoFractals
    BigBangRocket BigBangWorm
  )
  (libraries
    elm_playground
    elm_playground_native ; implem of virtual elm_playground
  )
)
