(executables
  (names 
    Picture Smiley Words Misc
    Animation 
    Mouse Keyboard Turtle Mario Typing GuiWidgets
    Gui7Counter Gui7Temperature Gui7Flight Gui7Timer GuiFourWays GuiEditor Gui7Circles Gui7Cells
    Flags
    PhysicsOrbit PhysicsBounce PhysicsMarbles PhysicsBoxes PhysicsPyramid PhysicsElastic PhysicsSolarSystem
    AudioTheremin AudioPiano
    AiTictactoe AiPathfinding
    LogoFractals
    BigBangRocket BigBangWorm
    PuzzleScriptSokoban PuzzleScriptBoulders
  )
  (libraries
    elm_playground
    ai ; AiTictactoe's Minimax
    gui ; GuiWidgets' Layout
    appkit_document ; Gui7Circles' Undo
    appkit_sheet ; Gui7Cells' engine
    appkit_sheet_view ; and how it is drawn
    elm_playground_native ; implem of virtual elm_playground
  )
)
