(library
 (public_name elm_playground_3d_webgl)
 (implements elm_playground_3d)
 (libraries
   js_of_ocaml ; WebGL, Dom_html, Typed_array
   elm_playground
   elm_playground_3d
   elm_playground_web ; its run_app, like elm_playground_3d_web
   graphics_3d_geometry ; Mat4, Lighting
   graphics_gpu ; Mesh_cache
 )
 (preprocess (pps js_of_ocaml-ppx))
)
