jobs:
  job:
    runs-on: ubuntu-20.04
    container:
      # living on the edge!
      image: semgrep/semgrep:pro-develop
    #TODO: at some point
    #env:
    #  SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    # ...
    # run: semgrep ci
    steps:
      - uses: actions/checkout@v3
      # TODO: not sure why we need that, the docker contain should do
      # similar things with ~root/.gitconfig
      - run: git config --global --add safe.directory /__w/ocaml-elm-playground/ocaml-elm-playground
      # coupling: with Makefile 'make check' target
      - run: semgrep scan --experimental --config semgrep.jsonnet --strict --error --debug

name: semgrep
on:
  # old was pull_request_target but has weird effect like not using
  # the latest change in this file
  pull_request: null
  workflow_dispatch: null
  push:
    branches:
      - master
  #schedule:
  #  - cron: 50 15 * * *
